# Generated by Django 4.2.4 on 2023-08-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words1', models.TextField()),
                ('words2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massiv', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=2)),
            ],
        ),
    ]
